### PR TITLE
Added Arbeitnow

### PR DESCRIPTION
**Pull request by adithyasrinivasan**
Thanks!

### CODE REVIEW

**Comment by faraazk69** [comment]
Just for an update Etsy is not hiring or giving visa sponsorship to international candidates because I have recently applied to this company and they rejected. So please remove Etsy if possible.

**Comment by faraazk69** [comment]
> Just for an update Etsy is not hiring or giving visa sponsorship to international candidates because I have recently applied to this company and they rejected. So please remove Etsy if possible.

Another update datadog and twilio are not hiring international candidates

**Comment by adithyasrinivasan** [comment]
Thanks @faraazk69 - I'll update it over the weekend!

**Comment by faraazk69** [comment]
> Thanks @faraazk69 - I'll update it over the weekend!

Another update Miro company is giving visa sponsorship to only EU citizens and not worldwide candidates, Savage interactive and Form3 also not giving visa sponsorship

**Pull request merged**
